# Generated by Django 4.0.1 on 2022-01-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyectoFinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutina',
            name='ejercicio_1',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicio_2',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicio_3',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicio_4',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicio_5',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicio_6',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicio_7',
            field=models.CharField(max_length=40),
        ),
    ]
